In [65]:
import numpy as np


In [66]:
arr=np.array([1,2,3],dtype='int32')
print(arr)

[1 2 3]


In [67]:
float_arr=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(float_arr)

[[9. 8. 7.]
 [6. 5. 4.]]


In [68]:
#get the dimention
arr.ndim

1

In [69]:
# Get Shape
float_arr.shape

(2, 3)

In [70]:
#get the type
arr.dtype

dtype('int32')

In [71]:
arr.itemsize  #will give single element size in bytes

4

In [72]:
arr.nbytes #array size in bytes

12

In [73]:
arr.size #will give number of element in arr

3

 **Accessing/Changing specific elements, rows, columns, etc**


In [75]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [76]:
# Get a specific element [r, c]
a[1, 5]

13

In [77]:

# Get a specific row ,getting first row, it is at 0th index
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
# get a specific column , here we are getting third column ,which is at index 2
a[:,2]

array([ 3, 10])

In [79]:

# Getting a little more fancy [startindex:endindex:stepsize]-->stepsize is for jumping
a[0, 1:6:2]

array([2, 4, 6])

In [80]:
# change element at index 1,5 
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


**3d array**

In [81]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [82]:

# Get specific element (work outside in)
b[0,1,1]

4

In [85]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


**Initializing Different Types of Arrays**

In [88]:

# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [90]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')  # it will create 4 array of size 2 by 2, you can go crazy over it

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [91]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [94]:

# Any other number (full_like) ,using shape of array a, a is define above cells
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [95]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.19126614, 0.25461779],
       [0.42502338, 0.8424347 ],
       [0.48857991, 0.53409186],
       [0.80228429, 0.14498907]])

In [99]:
np.random.random_sample(a.shape) # random element array with the shape

array([[0.28267823, 0.64082006, 0.70958877, 0.94320519, 0.66042318,
        0.79847243, 0.32992533],
       [0.49414739, 0.34598072, 0.31663446, 0.40582555, 0.34550251,
        0.95909192, 0.84879911]])

In [102]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) #range -4 to 8 and size 3 by 3 array

array([[-3,  3, -2],
       [-3, -3,  6],
       [ 6,  1,  6]])

In [103]:

# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Insert Function**

In [107]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)

[[1 1]
 [2 2]
 [3 3]]


In [110]:
np.insert(a, 2, 5) #inserting at index 2 

array([1, 1, 5, 2, 2, 3, 3])

In [109]:
np.insert(a, 1, 5, axis=1) #inserting by creating column at index 1

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [111]:
np.insert(a, 1, 5, axis=0) #inserting by creating row at index 1

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])